# Makefile for mysofa~

cflags =  -I/usr/local/include/ -mmacosx-version-min=10.15

ldflags = -L/usr/local/lib/ -lmysofa -lfftw3f -lm

lib.name = changesofa~

class.sources = changesofa~.c

datafiles = changesofa~-help.pd README.txt LICENSE.txt

include Makefile.pdlibbuilder

